### ISSUE TITLE
リスナー非表示設定をしてもpcgwのトップではリスナー数が見えてしまう

### ISSUE THREAD

**Issue by PyYoshi** [plonk/pcgw#1]
![pcyplite](https://cloud.githubusercontent.com/assets/467255/5951145/391e89c2-a7a6-11e4-89c6-458aa10a2ae8.jpg)
![pcgw](https://cloud.githubusercontent.com/assets/467255/5951147/3bb50ad0-a7a6-11e4-925c-8fcce1596fb8.jpg)

上記の他にindex.txt側も見えちゃってます.

確認お願いします.

**Comment by plonk** [comment]
トップページについては https://github.com/plonk/pcgw/commit/033b68798d0dcbb04767f9eff5f54dd7edb77693 で修正しました。

… index.txt もありましたね。YPと重複する情報なのでリスナーの役に立たないし、なくしてしまってもいいのだけれど。

**Comment by PyYoshi** [comment]
修正お疲れ様です.

index.txtの利用率どの程度か分からないですが, リスナーの需要は確かになさそうですね.
