### ISSUE TITLE
ナビバーのお知らせが崩れている

### ISSUE THREAD

**Issue by raduwen** [plonk/pcgw#15]
![image](https://user-images.githubusercontent.com/106211/84324729-1c91c680-abb4-11ea-9f71-b6d62d199b4f.png)

**Comment by plonk** [comment]
![2020-06-19-165458_1029x71_scrot](https://user-images.githubusercontent.com/1680210/85110325-b230f400-b24d-11ea-9701-f07807542bea.png)
直せました(^_^) https://github.com/plonk/pcgw/commit/0f8e47e28d2ac5bf20394fd59113c63f6470676d
